version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    container_name: drive-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]
volumes:
  data:
